language: haskell

before_install:
   - curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
  - stack --no-terminal --install-ghc test --only-dependencies

script:
  - stack --no-terminal --no-system-ghc test

cache:
  directories:
    - $HOME/.stack
    - .stack-work
